import React from 'react'
import './globals.css'
import localFont from 'next/font/local'

const infinity = localFont({
  src: './fonts/Cheap Potatoes Black Thin.ttf',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={infinity.className}>{children}</body>
    </html>
  )
}
