import React from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import './globals.css'
import localFont from 'next/font/local'

const infinity = localFont({
  src: './fonts/regular.otf',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={infinity.className}>{children}</body>
    </html>
  )
}
